GestorDocumentoApp/Models/Project.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;
namespace GestorDocumentoApp.Models
{
    public class Project
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string? Description { get; set; }
        public DateTime CreationDate { get; set; }

        [Required]
        public string UserId { get; set; }
        public IdentityUser User { get; set; }

        public List<Element> Elements { get; set; }

    }
}

GestorDocumentoApp/Controllers/ProjectController.cs
using GestorDocumentoApp.Data;
using GestorDocumentoApp.Models;
using GestorDocumentoApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using System.Threading.Tasks;

namespace GestorDocumentoApp.Controllers
{
    public class ProjectController : Controller
    {
        private readonly ScmDocumentContext _scmDocumentContext;
        private readonly ILogger<ElementTypeController> _logger;

        public ProjectController(ScmDocumentContext scmDocumentContext, ILogger<ElementTypeController> logger)
        {
            _scmDocumentContext = scmDocumentContext;
            _logger = logger;
        }


        public async Task<IActionResult> Index()
        {
            var useId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var projects = await _scmDocumentContext.Projects.Where(x => x.UserId == useId).OrderBy(project => project.Name).ToListAsync();
            return View(projects);

        }

        public IActionResult Create()
        {
            return View(new ProjectVM());
        }

        [HttpPost]
        public async Task<IActionResult> Create(ProjectVM projectVM)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(projectVM);
                }
                var project = new Project()
                {
                    Name = projectVM.Name,
                    Description = projectVM.Description,
                    CreationDate = DateTime.SpecifyKind(projectVM.CreationDate, DateTimeKind.Utc),
                    UserId = User.FindFirstValue(ClaimTypes.NameIdentifier)
                };
                _scmDocumentContext.Add(project);
                await _scmDocumentContext.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            catch (Exception ex)
            {
                _logger.LogError(ex, "Error saving Project {ProjectName}", projectVM.Name);

                return RedirectToAction(nameof(Index));
            }

        }


        public async Task<IActionResult> Edit([FromRoute] int id)
        {
            var project = await _scmDocumentContext.Projects.FindAsync(id);

            if (project is null)
            {
                return NotFound();
            }

            return View(new ProjectVM
            {
                Id = project.Id,
                Name = project.Name,
                Description = project.Description,
                CreationDate = project.CreationDate
            });

        }

        [HttpPost]
        public async Task<IActionResult> Edit([FromRoute] int id, ProjectVM projectVM)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(projectVM);
                }

                var project = await _scmDocumentContext.Projects.FindAsync(id);

                if (project is null)
                {
                    return NotFound();
                }

                project.Name = projectVM.Name;
                project.Description = projectVM.Description;
                project.CreationDate = DateTime.SpecifyKind(projectVM.CreationDate, DateTimeKind.Utc);

                await _scmDocumentContext.SaveChangesAsync();

                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error updating Project {ProjectName}", projectVM.Name);
                return RedirectToAction(nameof(Index));
            }

        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromRoute] int id)
        {
            try
            {
                var project = await _scmDocumentContext.Projects.FindAsync(id);

                if (project is null)
                {
                    return NotFound();
                }
                _scmDocumentContext.Projects.Remove(project);
                await _scmDocumentContext.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error delete Project {ProjectId}", id);
                return RedirectToAction(nameof(Index));
            }
        }

        public async Task<IActionResult> Show(int id)
        {
            var project = await _scmDocumentContext.Projects.AsNoTracking().Include(x => x.Elements.OrderByDescending(x=>x.CreatedDate)).ThenInclude(x=>x.Versions).Where(x => x.Id == id)
                .FirstOrDefaultAsync(x=>x.Id==id);
            if (project is null)
            {
                return NotFound();
            }
            return View(project);
        }

        public async Task<IActionResult> AsignElement(int id)
        {
            var project = await _scmDocumentContext.Projects.AsNoTracking().Include(x => x.Elements).FirstOrDefaultAsync(x => x.Id == id);
            if (project is null)
            {
                return NotFound();
            }

            var elementTypes = await _scmDocumentContext.ElementTypes.AsNoTracking().OrderBy(x => x.Name).ToListAsync();
            return View(new ProjectElementVM
            {
                Id = project.Id,
                ProjectName = project.Name,
                ElementTypes = elementTypes.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name.ToString() })

            });
        }

        [HttpPost]
        public async Task<IActionResult> AsignElement(int id, ProjectElementVM projectElementVM)
        {
            var project = await _scmDocumentContext.Projects.AsNoTracking().Include(x => x.Elements).FirstOrDefaultAsync(x => x.Id == id);
            if (project is null)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                var elementTypes = await _scmDocumentContext.ElementTypes.AsNoTracking().OrderBy(x => x.Name).ToListAsync();
                return View(new ProjectElementVM
                {
                    Id = project.Id,
                    ProjectName = project.Name,
                    ElementTypes = elementTypes.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name.ToString() })

                });
            }

            var element = new Element
            {
                Name = projectElementVM.ElementName,
                Description = projectElementVM.Description,
                CreatedDate = DateTime.SpecifyKind(projectElementVM.CreatedDate, DateTimeKind.Utc),
                ElementTypeId = projectElementVM.ElementTypeId,
                ProjectId = project.Id,
                ExternaCodeElement = projectElementVM.ExternaCodeElement,
                ExternalUrlElement = projectElementVM.ExternalUrlElement,
                
            };

            _scmDocumentContext.Add(element);
            await _scmDocumentContext.SaveChangesAsync();

            return RedirectToAction(nameof(Show), new { id = project.Id });
        }
    }
}

GestorDocumentoApp/Controllers/VersionController.cs
using GestorDocumentoApp.Data;
using GestorDocumentoApp.Models;
using GestorDocumentoApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;

namespace GestorDocumentoApp.Controllers
{
    public class VersionController : Controller
    {
        private readonly ScmDocumentContext _scmDocumentContext;
        private readonly ILogger<VersionController> _logger;

        public const string VERSION_STATE_ACTIVE = "active";
        public const string VERSION_STATE_INACTIVE = "inactive";

        public VersionController(ScmDocumentContext scmDocumentContext, ILogger<VersionController> logger)
        {
            _scmDocumentContext = scmDocumentContext;
            _logger = logger;
        }

        public async Task<IActionResult> Index(int elementId)
        {
            var element = await _scmDocumentContext.Elements.Include(x => x.Versions.OrderByDescending(x => x.UploadDate))
                .ThenInclude(x => x.ParentVersion)
                .ThenInclude(x => x.RequirementType).FirstOrDefaultAsync(x => x.Id == elementId);

            if (element == null)
            {
                return NotFound();
            }

            return View(element);


        }

        public async Task<IActionResult> Create(int elementId)
        {
            var element = await _scmDocumentContext.Elements.FindAsync(elementId);

            if (element is null)
            {
                return NotFound();
            }

            var requirementTypes = await _scmDocumentContext.RequirementTypes.AsNoTracking()
                .OrderBy(r => r.Name).ToListAsync();

            var versions = await _scmDocumentContext.Versions.AsNoTracking().Where(x => x.ElementId == element.Id)
                .OrderBy(v => v.VersionCode).ToListAsync();

            var changeRequests = await _scmDocumentContext.ChangeRequests
                .AsNoTracking()
                .Where(x => x.ElementId == element.Id)
                .Where(x => x.Action == ActionCR.Approved)
                .Where(x=>x.Status==StatusCR.Action).ToListAsync();

            return View(new VersionVM
            {
                ElementName = element.Name,
                ElementId = element.Id,
                RequirementTypes = requirementTypes.Select(r => new SelectListItem { Text = r.Name, Value = r.Id.ToString() }),
                PreviousVersions = versions.Select(v => new SelectListItem { Text = v.VersionCode + " | " + v.Id, Value = v.Id.ToString() }),
                ChangeRequests = changeRequests.Select(x => new SelectListItem { Text = x.Code, Value = x.Id.ToString() }),
                Phases = new SelectListItem[] {
                    new SelectListItem { Value="1",Text="Planificación"},
                    new SelectListItem { Value="2",Text="Análisis"},
                    new SelectListItem { Value="3",Text="Diseño"},
                    new SelectListItem { Value="4",Text="Implementación"},
                    new SelectListItem { Value="5",Text="Prueba"},
                    new SelectListItem { Value="6",Text="Mantenimiento"},
                }

            });
        }

        [HttpPost]
        public async Task<IActionResult> Create(int elementId, VersionVM versionVM)
        {
            try
            {
                var element = await _scmDocumentContext.Elements.FindAsync(elementId);

                if (element is null)
                {
                    return NotFound();
                }

                if (!ModelState.IsValid)
                {
                    await LoadDropDowns(versionVM);
                    return View(versionVM);
                }

                var version = new Models.Version
                {
                    Name = versionVM.Name,
                    ElementUrl = versionVM.ElementUrl,
                    UploadDate = DateTime.SpecifyKind(DateTime.Now, DateTimeKind.Utc),
                    State = VERSION_STATE_INACTIVE,
                    ToolUrl = versionVM.ToolUrl,
                    VersionCode = versionVM.VersionCode,
                    ElementId = element.Id,
                    ChangeRequestId = versionVM.ChangeRequestId.Value,
                    Phase = versionVM.Phase.Value,
                    iteration = versionVM.Iteration.Value,
                    UserId = User.FindFirstValue(ClaimTypes.NameIdentifier),
                    RequirementTypeId = versionVM.RequirementTypeId.Value,
                    ParentVersionId = versionVM.ParentVersionId
                };

                _scmDocumentContext.Add(version);
                await _scmDocumentContext.SaveChangesAsync();

                return RedirectToAction(nameof(Index), new { elementId = element.Id });
            }
            catch (DbUpdateException ex)
            {
                _logger.LogError(ex, "Error saving Version {VersionName}", versionVM.Name);

                TempData["Message"] = "El CR ya esta asociado a una version.";
                TempData["MessageType"] = "warning";

                return RedirectToAction(nameof(Index), new { elementId = elementId });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error saving Version {VersionName}", versionVM.Name);
                return RedirectToAction(nameof(Index), new { elementId = elementId });
            }
        }

        public async Task<IActionResult> Edit([FromRoute] int id)
        {
            var version = await _scmDocumentContext.Versions.FindAsync(id);

            if (version is null)
            {
                return NotFound();
            }

            var vm = new VersionVM
            {
                Id = version.Id,
                Name = version.Name,
                ElementId = version.ElementId,
                ElementName = version.Name,
                ElementUrl = version.ElementUrl,
                UploadDate = version.UploadDate,
                ChangeRequestId=version.ChangeRequestId,
                State = version.State,
                Phase = version.Phase,
                Iteration = version.iteration,
                ToolUrl = version.ToolUrl,
                VersionCode = version.VersionCode,

                RequirementTypeId = version.RequirementTypeId,
                ParentVersionId = version.ParentVersionId

            };

            await LoadDropDowns(vm);

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([FromRoute] int id, VersionVM versionVM)
        {
            try
            {
                var version = await _scmDocumentContext.Versions.FindAsync(id);

                if (version is null)
                {
                    return NotFound();
                }

                if (!ModelState.IsValid)
                {
                    await LoadDropDowns(versionVM);
                    return View(versionVM);
                }

                version.Name = versionVM.Name;
                version.ElementUrl = versionVM.ElementUrl;
                version.UploadDate = DateTime.SpecifyKind(DateTime.Now, DateTimeKind.Utc);
                version.ToolUrl = versionVM.ToolUrl;
                version.iteration = versionVM.Iteration.Value;
                version.Phase = versionVM.Phase.Value;
                version.ChangeRequestId = versionVM.ChangeRequestId.Value;
                version.VersionCode = versionVM.VersionCode;
                version.RequirementTypeId = versionVM.RequirementTypeId.Value;
                version.ParentVersionId = versionVM.ParentVersionId;

                await _scmDocumentContext.SaveChangesAsync();

                return RedirectToAction(nameof(Index), new { elementId = version.ElementId });
            }
            catch (DbUpdateException ex)
            {
                _logger.LogError(ex, "Error updating Version {VersionName}", versionVM.Name);

                TempData["Message"] = "El CR ya esta asociado a una version.";
                TempData["MessageType"] = "warning";

                return RedirectToAction(nameof(Index), new { elementId = versionVM.ElementName });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error saving Version {VersionName}", versionVM.Name);
                return RedirectToAction(nameof(Index), new { elementId = versionVM.ElementId });
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromRoute] int id)
        {
            try
            {
                var version = await _scmDocumentContext.Versions.FindAsync(id);

                if (version is null)
                {
                    return NotFound();
                }

                _scmDocumentContext.Versions.Remove(version);
                await _scmDocumentContext.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            catch (Exception ex)
            {
                _logger.LogError(ex, "Error deleting Version {VersionId}", id);
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpPost]
        public async Task<IActionResult> SetVersion(int id)
        {
            var version = await _scmDocumentContext.Versions.Include(x=>x.ChangeRequest).Where(x=>x.Id==id).FirstOrDefaultAsync();
            if (version is null)
            {
                TempData["Message"] = "No existe la version.";
                TempData["MessageType"] = "warning";
                return NotFound();
            }


            try
            {
                var activeVersion = await _scmDocumentContext.Versions
                    .Where(x => x.ElementId == version.ElementId).AnyAsync(x => x.State == VERSION_STATE_ACTIVE);

GestorDocumentoApp/Views/Project/AsignElement.cshtml
@model ProjectElementVM

@{
    ViewData["Title"] = "Project Page";
}
@await Html.PartialAsync("_HeaderTitle", new HeaderTitle { Title = "Proyecto: "+Model.ProjectName, Subtitle = "Formulario de creacion de elemento" })


<div class="mt-10">
    <form class="mx-auto w-full max-w-md" asp-action="AsignElement" method="post">
        <input asp-for="ProjectName" hidden/>
        <div class="group relative z-0 mb-5 w-full">

            <div class="sm:col-span-3">
                <label asp-form="ElementName" class="text-sm/6 block font-medium text-gray-900">Nombre</label>
                <div class="mt-2">
                    <input type="text" asp-for="ElementName" autocomplete="given-name" class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-blue-600 sm:text-sm/6" />
                </div>
            </div>
            <span asp-validation-for="ElementName" class="text-red-500"></span>

        </div>

        <div class="group relative z-0 mb-5 w-full">

            <div class="sm:col-span-3">
                <label asp-form="CreatedDate" class="text-sm/6 block font-medium text-gray-900">Fecha de creacion</label>
                <div class="mt-2">
                    <input type="datetime-local" step="60" asp-for="CreatedDate" autocomplete="given-name" class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-blue-600 sm:text-sm/6" value="@Model.CreatedDate.ToString("yyyy-MM-ddTHH:mm")" />
                </div>
            </div>
            <span asp-validation-for="CreatedDate" class="text-red-500"></span>

        </div>


        <div class="group relative mb-5">
            <div class="col-span-full">
                <label asp-for="Description" class="text-sm/6 block font-medium text-gray-900">Descripcion</label>
                <div class="mt-2">
                    <textarea asp-for="Description" rows="3" class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-blue-600 sm:text-sm/6"></textarea>
                </div>
            </div>
        </div>
        @Html.ValidationSummary(true, "", new { @class = "text-red-500" })
        

        <div class="mt-5">
            <label for="countries" class="mb-2 block text-sm font-medium text-gray-900">Seleccione una opcion</label>
            <select asp-for="ElementTypeId" asp-items="Model.ElementTypes" class="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-blue-600 focus:ring-blue-600">
                <option value="">-- Seleccione el tipo de elemento</option>
            </select>
        </div>

        <div class="mt-5 hidden" id="reposContainer">
            <label class="mb-2 text-sm font-medium text-gray-900">Seleccione una opcion</label>
            <select id="reposSelect" name="ExternaCodeElement" class="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-blue-600 focus:ring-blue-600">
            </select>
        </div>


        <div class="group relative z-0 mt-5 hidden w-full" id="containerUrl">

            <div class="sm:col-span-3">
                <label for="ExternalUrlElement" class="text-sm/6 block font-medium text-gray-900">Url</label>
                <div class="mt-2">
                    <input readonly type="text" id="ExternalUrlElement" name="ExternalUrlElement" autocomplete="given-name" class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-blue-600 sm:text-sm/6" />
                </div>
            </div>

        </div>



        <button type="submit"
                class="mt-5 max-w-fit rounded-lg bg-blue-700 px-5 py-2.5 text-center text-sm font-medium text-white focus:ring-4 focus:ring-blue-300 focus:outline-none sm:w-auto">
            Crear
        </button>
    </form>


</div> 

@section Scripts{
    <script src="~/js/Github.js"></script>
}

GestorDocumentoApp/Views/Project/Index.cshtml
@model List<Project>

@{
    ViewData["Title"] = "Project Page";
}

@await Html.PartialAsync("_HeaderTitle", new HeaderTitle { Title = "Proyectos", Subtitle = "Listado de proyectos" })


<div class="my-2 flex justify-end">
    <a asp-action="Create" class="rounded-md bg-blue-700 px-10 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-blue-800">
        Crear
    </a>
</div>

<table class="min-w-full">

    <thead class="border-b border-gray-100 bg-gray-200">
        <tr>
            <th scope="col"
            class="px-6 py-4 text-left text-sm font-medium text-gray-900">
                Id
            </th>
            <th scope="col"
            class="px-6 py-4 text-left text-sm font-medium text-gray-900">
                Nombre
            </th>


            <th scope="col"
                class="px-6 py-4 text-left text-sm font-medium text-gray-900">
                Fecha de creacion
            </th>

            <th scope="col"
            class="px-6 py-4 text-left text-sm font-medium text-gray-900">
                Descripcion
            </th>

            <th scope="col"
            class="px-6 py-4 text-left text-sm font-medium text-gray-900">
                Acciones
            </th>
        </tr>
    </thead>
    <tbody>

        @foreach (var project in Model)
        {
            <tr class="border-b border-gray-100 bg-white transition duration-300 ease-in-out hover:bg-gray-100">
                <td class="px-6 py-4 text-sm font-medium whitespace-nowrap text-gray-900">
                    @project.Id
                </td>

                <td class="px-6 py-4 text-sm whitespace-nowrap text-gray-900">
                    @project.Name
                </td>

                <td class="px-6 py-4 text-sm whitespace-nowrap text-gray-900">
                    @project.CreationDate.ToString("yyyy-MM-ddTHH:mm")
                </td>



                <td class="max-w-xs overflow-hidden px-6 py-4 text-sm text-ellipsis whitespace-nowrap text-gray-900">

                    @if (project.Description is null)
                    {
                        <text>Sin descripcion</text>
                    }
                    else
                    {
                        <text>@project.Description</text>
                    }
                    
                </td>

                <td class="flex items-center gap-3 px-6 py-4">

                    <a asp-action="Edit" asp-route-id="@project.Id"
                       class="text-blue-600 hover:text-blue-800 dark:text-blue-500 dark:hover:text-blue-400">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                             stroke-width="1.5" stroke="currentColor" class="inline h-5 w-5">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                  d="M16.862 4.487l1.687 1.687a1.5 1.5 0 010 2.121l-9.193 9.193a4.5 4.5 0 01-1.591.99l-3.41 1.137a.75.75 0 01-.948-.948l1.137-3.41a4.5 4.5 0 01.99-1.591l9.193-9.193a1.5 1.5 0 012.121 0z" />
                        </svg>
                    </a>

                    <a asp-action="Show" asp-route-id="@project.Id"
                       class="text-gray-600 hover:text-gray-800">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                             stroke-width="1.5" stroke="currentColor" class="inline h-5 w-5">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                  d="M4 6h16M4 12h16M4 18h16" />
                        </svg>
                    </a>

                    <form asp-action="Delete" asp-controller="Project" method="post"
                          asp-route-id="@project.Id" class="inline">
                        <button type="submit"
                                class="text-red-600 hover:text-red-800 dark:text-red-500 dark:hover:text-red-400">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                 stroke-width="1.5" stroke="currentColor" class="inline h-5 w-5">
                                <path stroke-linecap="round" stroke-linejoin="round"
                                      d="M6 18L18 6M6 6l12 12" />
                            </svg>
                        </button>
                    </form>
                </td>

            </tr>
        }


    </tbody>
</table>

GestorDocumentoApp/Views/Project/Show.cshtml
@model Project

@{
    ViewData["Title"] = "Project Page";
}

@await Html.PartialAsync("_HeaderTitle", new HeaderTitle { Title = "Proyecto: " + Model.Name, Subtitle = "Listado de ci's asignados" })



<div class="my-2 flex justify-end">
    <a asp-action="AsignElement" asp-route-id="@Model.Id" class="rounded-md bg-blue-700 px-10 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-blue-800">
        Crear
    </a>
</div>


<div class="mt-6 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-1 lg:grid-cols-3 xl:gap-x-8">
    @foreach (var element in Model.Elements)
    {
        <div class="group relative flex items-center gap-3 rounded-xl bg-white p-3 shadow transition hover:shadow-md">

            @if (element.Name.Contains("diseno", StringComparison.OrdinalIgnoreCase))
            {
                <img width="100" height="100" src="https://img.icons8.com/external-sbts2018-flat-sbts2018/58/external-design-civil-work-sbts2018-flat-sbts2018.png" alt="external-design-civil-work-sbts2018-flat-sbts2018" />
            }
            else if (element.Name.Contains("manual", StringComparison.OrdinalIgnoreCase))
            {
                <img width="100" height="100" src="https://img.icons8.com/color/96/user-manual.png" alt="user-manual" />
            }
            else if (element.Name.Contains("plan", StringComparison.OrdinalIgnoreCase))
            {
                <img width="100" height="100" src="https://img.icons8.com/color/96/user-manual.png" alt="user-manual" />
            }
            else
            {
                <img width="100" height="100" src="https://img.icons8.com/color/96/questions.png" alt="questions" />
            }

            <div class="flex flex-1 flex-col">

                <a asp-controller="Version" asp-action="Index" asp-route-elementId="@element.Id" class="text-gray-800 hover:text-blue-600">
                    @element.Name
                </a>

                @{
                    var versionActual = @element.Versions.Where(x => x.State == "active").FirstOrDefault();

                    if (versionActual is not null)
                    {
                        <span class="me-2 mt-1 w-fit rounded-sm bg-green-100 px-1 py-0.5 text-xs font-medium text-green-800">@PhaseHelper.GetPhaseName(versionActual.Phase) • @versionActual.iteration • @versionActual.VersionCode</span>
                    }
                }
            </div>


            <div class="flex flex-row gap-2">

                @if (element.ExternalUrlElement is not null)
                {
                    <a href="@element.ExternalUrlElement" title="Previsualizar enlace" target="_blank" rel="noopener noreferrer"
                       class="flex items-center justify-center rounded-full bg-blue-50 p-2 text-blue-600 transition hover:bg-blue-100">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"
                             class="h-6 w-6">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                  d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                  d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                        </svg>
                    </a>
                }

                
                <a asp-action="CreateByElement" asp-controller="ChangeRequest" asp-route-id="@element.Id" title="Agregar cambio"
                    class="flex items-center justify-center rounded-full bg-green-50 p-2 text-green-600 transition hover:bg-green-100">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"
                        class="h-6 w-6">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M9 2a1 1 0 00-1 1v1H5a2 2 0 00-2 2v14a2 2 0 002 2h14a2 2 0 002-2V6a2 2 0 00-2-2h-3V3a1 1 0 00-1-1H9z" />
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6" />
                    </svg>
                </a>

            </div>
        </div>
    }
</div>