GestorDocumentoApp/Controllers/ElementTypeController.cs
using GestorDocumentoApp.Data;
using GestorDocumentoApp.Extensions;
using GestorDocumentoApp.Models;
using GestorDocumentoApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GestorDocumentoApp.Controllers
{
    public class ElementTypeController : Controller
    {
        private readonly ScmDocumentContext _scmDocumentContext;
        private readonly ILogger<ElementTypeController> _logger;

        public ElementTypeController(ScmDocumentContext scmDocumentContext, ILogger<ElementTypeController> logger)
        {
            _scmDocumentContext = scmDocumentContext;
            _logger = logger;
        }


        public async Task<IActionResult> Index( int pageNumber = 1, int pageSize = 10)
        {
            if (pageNumber < 1)
            {
                pageNumber = 1;
            }

            if (pageSize < 1)
            {
                pageSize = 10;
            }

            var elementTypes = await _scmDocumentContext.ElementTypes
                .AsNoTracking().OrderBy(elementType => elementType.Name)
                .ToPagedListAsync(pageNumber,pageSize);
            
            return View(elementTypes);

        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ElementTypeVM elementTypeVM)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(elementTypeVM);
                }
                var elementType = new ElementType() { Name = elementTypeVM.Name, Description = elementTypeVM.Description };
                _scmDocumentContext.Add(elementType);
                await _scmDocumentContext.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            catch (Exception ex)
            {
                _logger.LogError(ex, "Error saving Element Type {ElementName}", elementTypeVM.Name);

                return RedirectToAction(nameof(Index));
            }

        }


        public async Task<IActionResult> Edit([FromRoute] int id)
        {
            var elementType = await _scmDocumentContext.ElementTypes.FindAsync(id);

            if (elementType is null)
            {
                return NotFound();
            }

            return View(new ElementTypeVM { Id = elementType.Id, Name = elementType.Name, Description = elementType.Description });

        }

        [HttpPost]
        public async Task<IActionResult> Edit([FromRoute] int id, ElementTypeVM elementTypeVM)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(elementTypeVM);
                }

                var elementType = await _scmDocumentContext.ElementTypes.FindAsync(id);
                
                if(elementType is null)
                {
                    return NotFound();
                }

                elementType.Name = elementTypeVM.Name;
                elementType.Description = elementTypeVM.Description;

                await _scmDocumentContext.SaveChangesAsync();

                return RedirectToAction(nameof(Index));

            }catch(Exception ex)
            {
                _logger.LogError(ex, "Error updating Element Type {ElementName}", elementTypeVM.Name);
                return RedirectToAction(nameof(Index));
            }

        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromRoute] int id)
        {
            try
            {
                var elementType = await _scmDocumentContext.ElementTypes.FindAsync(id);

                if(elementType is null)
                {
                    return NotFound();
                }
                _scmDocumentContext.ElementTypes.Remove(elementType);
                await _scmDocumentContext.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error delete Element Type {ElementId}", id);
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

GestorDocumentoApp/Views/ElementType/Create.cshtml
@model ElementTypeVM
@{
    ViewData["Title"] = "Element Type Page";
}
@await Html.PartialAsync("_HeaderTitle", new HeaderTitle { Title = "Tipo de elemento", Subtitle = "Formulario de creacion" })


<div class="mt-10">
    <form class="mx-auto w-full max-w-md" asp-action="Create" method="post">
        
        <div class="group relative z-0 mb-5 w-full">

            <div class="sm:col-span-3">
                <label asp-form="Name" class="text-sm/6 block font-medium text-gray-900">Nombre</label>
                <div class="mt-2">
                    <input  type="text" asp-for="Name" autocomplete="given-name" class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-blue-600 sm:text-sm/6" />
                </div>
            </div>
            <span asp-validation-for="Name" class="text-red-500"></span>

        </div>
        
        <div class="group relative z-0 mb-5 w-full">
            <div class="col-span-full">
                <label asp-for="Description" class="text-sm/6 block font-medium text-gray-900">Descripcion</label>
                <div class="mt-2">
                    <textarea asp-for="Description" rows="3" class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-blue-600 sm:text-sm/6"></textarea>
                </div>
            </div>
        </div>


        <button type="submit"
                class="max-w-fit rounded-lg bg-blue-700 px-5 py-2.5 text-center text-sm font-medium text-white focus:ring-4 focus:ring-blue-300 focus:outline-none sm:w-auto">
            Crear
        </button>
    </form>


</div> 

GestorDocumentoApp/Views/ElementType/Edit.cshtml
@model ElementTypeVM
@{
    ViewData["Title"] = "Element Type Page";
}


@await Html.PartialAsync("_HeaderTitle",new HeaderTitle{Title="Tipo de elemento",Subtitle="Formulario de edicion"})

<div>
    <form class="mx-auto w-full max-w-md" asp-action="Edit" method="post" asp-route-id="@Model.Id">

        <div class="group relative z-0 mb-5 w-full">

            <div class="sm:col-span-3">
                <label asp-form="Name" class="text-sm/6 block font-medium text-gray-900">Nombre</label>
                <div class="mt-2">
                    <input type="text" asp-for="Name" autocomplete="given-name" class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-blue-600 sm:text-sm/6" />
                </div>
            </div>
            <span asp-validation-for="Name" class="text-red-500"></span>

        </div>

        <div class="group relative z-0 mb-5 w-full">
            <div class="col-span-full">
                <label asp-for="Description" class="text-sm/6 block font-medium text-gray-900">Descripcion</label>
                <div class="mt-2">
                    <textarea asp-for="Description" rows="3" class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-blue-600 sm:text-sm/6"></textarea>
                </div>
            </div>
        </div>


        <button type="submit"
                class="max-w-fit rounded-lg bg-blue-700 px-5 py-2.5 text-center text-sm font-medium text-white focus:ring-4 focus:ring-blue-300 focus:outline-none sm:w-auto">
            Actualizar
        </button>
    </form>


</div> 

GestorDocumentoApp/Views/ElementType/Index.cshtml
@model PagedList<ElementType>

@{
    ViewData["Title"] = "Element Type Page";
}

@await Html.PartialAsync("_HeaderTitle", new HeaderTitle { Title = "Tipo de elemento", Subtitle = "Listado de tipo de elementos" })


<div class="my-2 flex justify-end">
    <a asp-action="Create" class="rounded-md bg-blue-700 px-10 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-blue-800">
        Crear
    </a>
</div>

<table class="min-w-full">

    <thead class="border-b border-gray-100 bg-gray-200">
        <tr>
            <th scope="col"
                class="px-6 py-4 text-left text-sm font-medium text-gray-900">
                Id
            </th>
            <th scope="col"
                class="px-6 py-4 text-left text-sm font-medium text-gray-900">
                Nombre
            </th>

            <th scope="col"
                class="px-6 py-4 text-left text-sm font-medium text-gray-900">
                Descripcion
            </th>

            <th scope="col"
                class="px-6 py-4 text-left text-sm font-medium text-gray-900">
                Acciones
            </th>
        </tr>
    </thead>
    <tbody>

        @foreach (var elementType in Model.Items)
        {
            <tr class="border-b border-gray-100 bg-white transition duration-300 ease-in-out hover:bg-gray-100">
                <td class="px-6 py-4 text-sm font-medium whitespace-nowrap text-gray-900">
                    @elementType.Id
                </td>

                <td class="px-6 py-4 text-sm whitespace-nowrap text-gray-900">
                    @elementType.Name
                </td>

                <td class="max-w-xs overflow-hidden px-6 py-4 text-sm text-ellipsis whitespace-nowrap text-gray-900">

                    @if (elementType.Description is null)
                    {
                        <text>Sin descripcion</text>
                    }
                    else
                    {
                        <text>@elementType.Description</text>
                    }

                </td>

                <td class="flex items-center gap-3 px-6 py-3">

                    <a asp-action="Edit" asp-route-id="@elementType.Id"
                       class="text-blue-600 hover:text-blue-800 dark:text-blue-500 dark:hover:text-blue-400">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                             stroke-width="1.5" stroke="currentColor" class="inline h-5 w-5">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                  d="M16.862 4.487l1.687 1.687a1.5 1.5 0 010 2.121l-9.193 9.193a4.5 4.5 0 01-1.591.99l-3.41 1.137a.75.75 0 01-.948-.948l1.137-3.41a4.5 4.5 0 01.99-1.591l9.193-9.193a1.5 1.5 0 012.121 0z" />
                        </svg>
                    </a>

                    <form asp-controller="ElementType" asp-action="Delete" method="post"
                          asp-route-id="@elementType.Id" class="inline">
                        <button type="submit"
                                class="text-red-600 hover:text-red-800 dark:text-red-500 dark:hover:text-red-400">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                 stroke-width="1.5" stroke="currentColor" class="inline h-5 w-5">
                                <path stroke-linecap="round" stroke-linejoin="round"
                                      d="M6 18L18 6M6 6l12 12" />
                            </svg>
                        </button>
                    </form>

                </td>

            </tr>
        }


    </tbody>
</table>

@await Html.PartialAsync("_Pagination", new
    {
        TotalCount = Model.TotalCount,
        HasPrevious = Model.HasPrevious,
        PageNumber = Model.PageNumber,
        HasNext = Model.HasNext,
        PageSize = Model.PageSize
    })