GestorDocumentoApp/ViewModels/HeaderTitle.cs
namespace GestorDocumentoApp.ViewModels
{
    public class HeaderTitle
    {
        public string Title { get; set; }
        public string Subtitle { get; set; }
    }
}

GestorDocumentoApp/Controllers/ElementController.cs
using GestorDocumentoApp.Data;
using GestorDocumentoApp.Extensions;
using GestorDocumentoApp.Models;
using GestorDocumentoApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace GestorDocumentoApp.Controllers
{
    public class ElementController : Controller
    {
        private ScmDocumentContext _scmDocumentContext;
        private ILogger<ElementController> _logger;

        public ElementController(ScmDocumentContext scmDocumentContext, ILogger<ElementController> logger)
        {
            _scmDocumentContext = scmDocumentContext;
            _logger = logger;
        }

        public async Task<IActionResult> Index(int? projectId, int pageNumber = 1, int pageSize = 10)
        {
            Project? project = null;

            if (projectId.HasValue)
            {
                project=await _scmDocumentContext.Projects.FindAsync(projectId);

                if (project is null)
                {
                    return NotFound();
                }
            }

            var projects=await _scmDocumentContext.Projects.AsNoTracking().ToListAsync();

            IQueryable<Element> query = _scmDocumentContext.Elements;

            if (projectId.HasValue)
            {
                query=query.Where(x => x.ProjectId == projectId);
            }

            var page = await query
                .Include(x => x.Project).Include(x => x.ElementType)
                .OrderByDescending(element => element.CreatedDate).ToPagedListAsync(pageNumber, pageSize);

            return View(
                new ElementIndexVM
                {
                    Projects=projects.Select(x =>new SelectListItem { Value=x.Id.ToString(),Text=x.Name.ToString()}),
                    HasNext=page.HasNext,
                    HasPrevious=page.HasPrevious,
                    Items=page.Items,
                    TotalCount=page.TotalCount,
                    PageNumber=pageNumber,
                    PageSize=pageSize,
                    ProjectId=projectId,
                    ProjectName=project?.Name
                }
                );
        }

        public async Task<IActionResult> Create()
        {

            var elementTypes = await _scmDocumentContext.ElementTypes.AsNoTracking().OrderBy(elementType => elementType.Name).ToListAsync();
            var projects = await _scmDocumentContext.Projects.AsNoTracking().OrderBy(x => x.Name).ToListAsync();


            return View(
                new ElementVM
                {
                    ElementTypes = elementTypes.Select(elementType => new SelectListItem { Text = elementType.Name, Value = elementType.Id.ToString() }),
                    Projects = projects.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() }),
                }
            );
        }

        [HttpPost]
        public async Task<IActionResult> Create(ElementVM elementVM)
        {
            try
            {
                if (!ModelState.IsValid)
                {

                    var elementTypes = await _scmDocumentContext.ElementTypes.AsNoTracking().OrderBy(elementType => elementType.Name).ToListAsync();
                    var projects = await _scmDocumentContext.Projects.AsNoTracking().OrderBy(x => x.Name).ToListAsync();

                    elementVM.ElementTypes = elementTypes.Select(elementType => new SelectListItem { Text = elementType.Name, Value = elementType.Id.ToString() });
                    elementVM.Projects = projects.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() });

                    return View(elementVM);
                }
                var element = new Element
                {
                    Name = elementVM.Name,
                    Description = elementVM.Description,
                    CreatedDate = DateTime.SpecifyKind(elementVM.CreatedDate, DateTimeKind.Utc),

                    ElementTypeId = elementVM.ElementTypeId,
                    ProjectId = elementVM.ProjectId.Value,
                };

                _scmDocumentContext.Add(element);
                await _scmDocumentContext.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            catch (Exception ex)
            {
                _logger.LogError(ex, "Error saving Element Type {ElementName}", elementVM.Name);

                return RedirectToAction(nameof(Index));
            }

        }


        public async Task<IActionResult> Edit([FromRoute] int id)
        {
            var element = await _scmDocumentContext.Elements.FindAsync(id);

            if (element is null)
            {
                return NotFound();
            }

            var elementTypes = await _scmDocumentContext.ElementTypes.AsNoTracking().OrderBy(element => element.Name).ToListAsync();

            var projects = await _scmDocumentContext.Projects.AsNoTracking().OrderBy(x => x.Name).ToListAsync();

            return View(
                new ElementVM
                {
                    Id = element.Id,
                    Name = element.Name,
                    Description = element.Description,
                    CreatedDate = element.CreatedDate,
                    ElementTypeId = element.ElementTypeId,

                    ProjectId = element.ProjectId,
                    ElementTypes = elementTypes.Select(elementType => new SelectListItem { Text = elementType.Name, Value = elementType.Id.ToString() }),
                    Projects = projects.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() }),
                }

                );

        }

        [HttpPost]
        public async Task<IActionResult> Edit([FromRoute] int id, ElementVM elementVM)
        {
            try
            {

                var element = await _scmDocumentContext.Elements.FindAsync(id);

                if (element is null)
                {
                    return NotFound();
                }

                if (!ModelState.IsValid)
                {
                    var elementTypes = await _scmDocumentContext.ElementTypes.OrderBy(elementType => elementType.Name).ToListAsync();
                    var projects = await _scmDocumentContext.Projects.AsNoTracking().OrderBy(x => x.Name).ToListAsync();

                    elementVM.ElementTypes = elementTypes.Select(elementType => new SelectListItem { Text = elementType.Name, Value = elementType.Id.ToString() });
                    elementVM.Projects = projects.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() });

                    return View(elementVM);
                }

                if (element is null)
                {
                    return NotFound();
                }

                element.Name = elementVM.Name;
                element.Description = elementVM.Description;
                element.CreatedDate = DateTime.SpecifyKind(elementVM.CreatedDate, DateTimeKind.Utc);
                element.ElementTypeId = elementVM.ElementTypeId;

                element.ProjectId = elementVM.ProjectId.Value;

                await _scmDocumentContext.SaveChangesAsync();

                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error updating Element {ElementName}", elementVM.Name);
                return RedirectToAction(nameof(Index));
            }

        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromRoute] int id)
        {
            try
            {
                var element = await _scmDocumentContext.Elements.FindAsync(id);

                if (element is null)
                {
                    return NotFound();
                }
                _scmDocumentContext.Elements.Remove(element);
                await _scmDocumentContext.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error delete Element {ElementId}", id);
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

GestorDocumentoApp/Controllers/ProjectController.cs
using GestorDocumentoApp.Data;
using GestorDocumentoApp.Models;
using GestorDocumentoApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using System.Threading.Tasks;

namespace GestorDocumentoApp.Controllers
{
    public class ProjectController : Controller
    {
        private readonly ScmDocumentContext _scmDocumentContext;
        private readonly ILogger<ElementTypeController> _logger;

        public ProjectController(ScmDocumentContext scmDocumentContext, ILogger<ElementTypeController> logger)
        {
            _scmDocumentContext = scmDocumentContext;
            _logger = logger;
        }


        public async Task<IActionResult> Index()
        {
            var useId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var projects = await _scmDocumentContext.Projects.Where(x => x.UserId == useId).OrderBy(project => project.Name).ToListAsync();
            return View(projects);

        }

        public IActionResult Create()
        {
            return View(new ProjectVM());
        }

        [HttpPost]
        public async Task<IActionResult> Create(ProjectVM projectVM)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(projectVM);
                }
                var project = new Project()
                {
                    Name = projectVM.Name,
                    Description = projectVM.Description,
                    CreationDate = DateTime.SpecifyKind(projectVM.CreationDate, DateTimeKind.Utc),
                    UserId = User.FindFirstValue(ClaimTypes.NameIdentifier)
                };
                _scmDocumentContext.Add(project);
                await _scmDocumentContext.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            catch (Exception ex)
            {
                _logger.LogError(ex, "Error saving Project {ProjectName}", projectVM.Name);

                return RedirectToAction(nameof(Index));
            }

        }


        public async Task<IActionResult> Edit([FromRoute] int id)
        {
            var project = await _scmDocumentContext.Projects.FindAsync(id);

            if (project is null)
            {
                return NotFound();
            }

            return View(new ProjectVM
            {
                Id = project.Id,
                Name = project.Name,
                Description = project.Description,
                CreationDate = project.CreationDate
            });

        }

        [HttpPost]
        public async Task<IActionResult> Edit([FromRoute] int id, ProjectVM projectVM)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(projectVM);
                }

                var project = await _scmDocumentContext.Projects.FindAsync(id);

                if (project is null)
                {
                    return NotFound();
                }

                project.Name = projectVM.Name;
                project.Description = projectVM.Description;
                project.CreationDate = DateTime.SpecifyKind(projectVM.CreationDate, DateTimeKind.Utc);

                await _scmDocumentContext.SaveChangesAsync();

                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error updating Project {ProjectName}", projectVM.Name);
                return RedirectToAction(nameof(Index));
            }

        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromRoute] int id)
        {
            try
            {
                var project = await _scmDocumentContext.Projects.FindAsync(id);

                if (project is null)
                {
                    return NotFound();
                }
                _scmDocumentContext.Projects.Remove(project);
                await _scmDocumentContext.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error delete Project {ProjectId}", id);
                return RedirectToAction(nameof(Index));
            }
        }

        public async Task<IActionResult> Show(int id)
        {
            var project = await _scmDocumentContext.Projects.AsNoTracking().Include(x => x.Elements.OrderByDescending(x=>x.CreatedDate)).ThenInclude(x=>x.Versions).Where(x => x.Id == id)
                .FirstOrDefaultAsync(x=>x.Id==id);
            if (project is null)
            {
                return NotFound();
            }
            return View(project);
        }

        public async Task<IActionResult> AsignElement(int id)
        {
            var project = await _scmDocumentContext.Projects.AsNoTracking().Include(x => x.Elements).FirstOrDefaultAsync(x => x.Id == id);
            if (project is null)
            {
                return NotFound();
            }

            var elementTypes = await _scmDocumentContext.ElementTypes.AsNoTracking().OrderBy(x => x.Name).ToListAsync();
            return View(new ProjectElementVM
            {
                Id = project.Id,
                ProjectName = project.Name,
                ElementTypes = elementTypes.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name.ToString() })

            });
        }

        [HttpPost]
        public async Task<IActionResult> AsignElement(int id, ProjectElementVM projectElementVM)
        {
            var project = await _scmDocumentContext.Projects.AsNoTracking().Include(x => x.Elements).FirstOrDefaultAsync(x => x.Id == id);
            if (project is null)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                var elementTypes = await _scmDocumentContext.ElementTypes.AsNoTracking().OrderBy(x => x.Name).ToListAsync();
                return View(new ProjectElementVM
                {
                    Id = project.Id,
                    ProjectName = project.Name,
                    ElementTypes = elementTypes.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name.ToString() })

                });
            }

            var element = new Element
            {
                Name = projectElementVM.ElementName,
                Description = projectElementVM.Description,
                CreatedDate = DateTime.SpecifyKind(projectElementVM.CreatedDate, DateTimeKind.Utc),
                ElementTypeId = projectElementVM.ElementTypeId,
                ProjectId = project.Id,
                ExternaCodeElement = projectElementVM.ExternaCodeElement,
                ExternalUrlElement = projectElementVM.ExternalUrlElement,
                
            };

            _scmDocumentContext.Add(element);
            await _scmDocumentContext.SaveChangesAsync();

            return RedirectToAction(nameof(Show), new { id = project.Id });
        }
    }
}

GestorDocumentoApp/Views/Shared/_HeaderTitle.cshtml
@model HeaderTitle

<div class="mb-4 text-lg">
    <h1 class="font-semibold antialiased">
        @Model.Title
    </h1>

    <h3>@Model.Subtitle</h3>
</div>

GestorDocumentoApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GestorDocumentoApp</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/css/output.css" asp-append-version="true" />
</head>
<body class="mx-auto h-screen max-w-7xl">
    <header>
        <partial name="_Navbar"/>
    </header>

    <div class="mx-8 flex flex-col">
        <main>
            @RenderBody()
        </main>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js" defer></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

GestorDocumentoApp/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Login</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/css/output.css" asp-append-version="true" />
</head>
<body>

    <div>
        <main>
            @RenderBody()
        </main>
    </div>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GestorDocumentoApp/Views/Shared/_Navbar.cshtml
<nav class="flex items-center justify-between p-4">
    <div>
        <a href="/" class="text-lg">
            <span class="font-bold antialiased">
                SCM Document
            </span>
            <span class="font-bold antialiased">
                | App
            </span>
        </a>
    </div>


    <div class="flex gap-x-12">

        <a asp-action="Index" asp-controller="Project"  class="font-semibold text-gray-900">
        Proyectos
        </a>

        <a asp-action="Index" asp-controller="Element" class="font-semibold text-gray-900">
        Elementos
        </a>
        
    </div>

    <div x-data="{ open: false }" class="relative">
        <button type="button"
                x-on:click="open = !open"
                class="text-sm/6 flex items-center gap-x-1 font-semibold text-gray-900 focus:outline-none">
            <!-- icono -->
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                 stroke-width="1.5" stroke="currentColor" class="h-7 w-7">
                <path stroke-linecap="round" stroke-linejoin="round"
                      d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
            </svg>
        </button>

        <div x-show="open"
             x-on:click.outside="open = false"
             x-transition
             class="absolute top-6 -left-44 z-10 w-44 divide-y divide-gray-100 rounded-lg bg-white shadow">
            <div class="p-4">
                <div class="px-4 py-3 text-sm text-gray-900">
                    <div>@(User?.Identity?.Name ?? "Invitado")</div>
                    <div class="font-medium">Nombre de usuario</div>
                </div>

                <ul class="text-sm text-gray-700" aria-labelledby="menuButton">
                    <li><a asp-controller="Dashboard" asp-action="Index" class="block px-4 py-2 hover:bg-gray-100">Dashboard</a></li>
                    <li><a asp-controller="Settings" asp-action="Index" class="block px-4 py-2 hover:bg-gray-100">Configuración</a></li>
                </ul>

                <div>
                    <form asp-controller="Account" asp-action="Logout" method="post">
                        <button type="submit" class="block w-full px-4 py-2 text-left text-sm text-gray-700 hover:bg-gray-100">Salir</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</nav>

GestorDocumentoApp/Views/Shared/_Pagination.cshtml
@if(Model.TotalCount>0){
<div class="mt-5 flex justify-end">
    <nav aria-label="Pagination" class="isolate inline-flex -space-x-px rounded-md shadow-xs">
        @if (Model.HasPrevious)
        {
            <a asp-route-pageNumber="@(Model.PageNumber-1)" asp-route-pageSize="@Model.PageSize" class="relative inline-flex items-center rounded-l-md px-2 py-2 text-gray-400 inset-ring inset-ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0">
                <span class="sr-only">Previous</span>
                <svg viewBox="0 0 20 20" fill="currentColor" data-slot="icon" aria-hidden="true" class="size-5">
                    <path d="M11.78 5.22a.75.75 0 0 1 0 1.06L8.06 10l3.72 3.72a.75.75 0 1 1-1.06 1.06l-4.25-4.25a.75.75 0 0 1 0-1.06l4.25-4.25a.75.75 0 0 1 1.06 0Z" clip-rule="evenodd" fill-rule="evenodd" />
                </svg>
            </a>
        }



        <a href="#" aria-current="page" class="relative z-10 inline-flex items-center bg-indigo-600 px-4 py-2 text-sm font-semibold text-white focus:z-20 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">@Model.PageNumber</a>

        @if (Model.HasNext)
        {
            <a asp-route-pageNumber="@(Model.PageNumber+1)" asp-route-pageSize="@Model.PageSize" class="relative inline-flex items-center rounded-r-md px-2 py-2 text-gray-400 inset-ring inset-ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0">
                <span class="sr-only">Next</span>
                <svg viewBox="0 0 20 20" fill="currentColor" data-slot="icon" aria-hidden="true" class="size-5">
                    <path d="M8.22 5.22a.75.75 0 0 1 1.06 0l4.25 4.25a.75.75 0 0 1 0 1.06l-4.25 4.25a.75.75 0 0 1-1.06-1.06L11.94 10 8.22 6.28a.75.75 0 0 1 0-1.06Z" clip-rule="evenodd" fill-rule="evenodd" />
                </svg>
            </a>
        }
    </nav>
</div>
}